#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Dec 23, 2025 04:00:30 PM CST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import IAP_tools_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: IAP_tools_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'default.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('default')
    style.configure('.', font = "TkDefaultFont")
    if sys.platform == "win32":
       style.theme_use('winnative')    
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1000x600+246+166")
        top.minsize(120, 1)
        top.maxsize(1920, 1080)
        top.resizable(1,  1)
        top.title("IAP_tools")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top
        self.combobox = tk.StringVar()
        self.COMSelect = tk.StringVar()
        self.BaudRateSelect = tk.StringVar()
        self.che76 = tk.IntVar()

        _style_code()
        self.DownloadTProgressbar = ttk.Progressbar(self.top)
        self.DownloadTProgressbar.place(relx=0.022, rely=0.867, relwidth=0.811
                , relheight=0.0, height=19)
        self.DownloadTProgressbar.configure(length="730")

        self.Connect_State_Labe = ttk.Labelframe(self.top)
        self.Connect_State_Labe.place(relx=0.844, rely=0.767, relheight=0.225
                , relwidth=0.142)
        self.Connect_State_Labe.configure(relief='')
        self.Connect_State_Labe.configure(text='''State''')

        self.Connect_State = tk.Label(self.Connect_State_Labe)
        self.Connect_State.place(relx=0.352, rely=0.444, height=23, width=41
                , bordermode='ignore')
        self.Connect_State.configure(activebackground="#d9d9d9")
        self.Connect_State.configure(activeforeground="black")
        self.Connect_State.configure(anchor='w')
        self.Connect_State.configure(background="#d9d9d9")
        self.Connect_State.configure(compound='left')
        self.Connect_State.configure(disabledforeground="#a3a3a3")
        self.Connect_State.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.Connect_State.configure(foreground="#000000")
        self.Connect_State.configure(highlightbackground="#d9d9d9")
        self.Connect_State.configure(highlightcolor="#000000")
        self.Connect_State.configure(text='''State''')

        self.Log = ttk.Labelframe(self.top)
        self.Log.place(relx=0.022, rely=0.267, relheight=0.575, relwidth=0.811)
        self.Log.configure(relief='')
        self.Log.configure(text='''Log''')

        self.Message = ScrolledText(self.Log)
        self.Message.place(relx=0.014, rely=0.072, relheight=0.87, relwidth=0.975
                , bordermode='ignore')
        self.Message.configure(background="white")
        self.Message.configure(font="TkTextFont")
        self.Message.configure(foreground="black")
        self.Message.configure(highlightbackground="#d9d9d9")
        self.Message.configure(highlightcolor="#000000")
        self.Message.configure(insertbackground="#000000")
        self.Message.configure(insertborderwidth="3")
        self.Message.configure(selectbackground="#d9d9d9")
        self.Message.configure(selectforeground="black")
        self.Message.configure(wrap="none")

        self.Control = ttk.Labelframe(self.top)
        self.Control.place(relx=0.022, rely=0.033, relheight=0.208
                , relwidth=0.956)
        self.Control.configure(relief='')
        self.Control.configure(text='''Control''')

        self.Open_Port = tk.Button(self.Control)
        self.Open_Port.place(relx=0.879, rely=0.16, height=40, width=99
                , bordermode='ignore')
        self.Open_Port.configure(activebackground="#d9d9d9")
        self.Open_Port.configure(activeforeground="black")
        self.Open_Port.configure(background="#d9d9d9")
        self.Open_Port.configure(disabledforeground="#a3a3a3")
        self.Open_Port.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.Open_Port.configure(foreground="#000000")
        self.Open_Port.configure(highlightbackground="#d9d9d9")
        self.Open_Port.configure(highlightcolor="#000000")
        self.Open_Port.configure(text='''Open_Port''')

        self.Open_file = tk.Button(self.Control)
        self.Open_file.place(relx=0.879, rely=0.592, height=40, width=99
                , bordermode='ignore')
        self.Open_file.configure(activebackground="#d9d9d9")
        self.Open_file.configure(activeforeground="black")
        self.Open_file.configure(background="#d9d9d9")
        self.Open_file.configure(disabledforeground="#a3a3a3")
        self.Open_file.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.Open_file.configure(foreground="#000000")
        self.Open_file.configure(highlightbackground="#d9d9d9")
        self.Open_file.configure(highlightcolor="#000000")
        self.Open_file.configure(text='''Open_file''')

        self.Text1 = tk.Text(self.Control)
        self.Text1.place(relx=0.01, rely=0.664, relheight=0.24, relwidth=0.837
                , bordermode='ignore')
        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="#000000")
        self.Text1.configure(insertbackground="#000000")
        self.Text1.configure(selectbackground="#d9d9d9")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(wrap="word")

        self.Port_Select = ttk.Combobox(self.Control)
        self.Port_Select.place(relx=0.063, rely=0.24, relheight=0.232
                , relwidth=0.113, bordermode='ignore')
        self.Port_Select.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.Port_Select.configure(textvariable=self.combobox)

        self.COM_Select = ttk.Combobox(self.Control)
        self.COM_Select.place(relx=0.262, rely=0.24, relheight=0.232
                , relwidth=0.332, bordermode='ignore')
        self.COM_Select.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.COM_Select.configure(textvariable=self.COMSelect)

        self.Label3 = tk.Label(self.Control)
        self.Label3.place(relx=0.617, rely=0.24, height=30, width=64
                , bordermode='ignore')
        self.Label3.configure(activebackground="#d9d9d9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="#000000")
        self.Label3.configure(text='''Baudrate:''')

        self.Label2 = tk.Label(self.Control)
        self.Label2.place(relx=0.209, rely=0.24, height=31, width=41
                , bordermode='ignore')
        self.Label2.configure(activebackground="#d9d9d9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="#000000")
        self.Label2.configure(text='''COM:''')

        self.Label1 = tk.Label(self.Control)
        self.Label1.place(relx=0.016, rely=0.24, height=30, width=41
                , bordermode='ignore')
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(text='''Port:''')

        self.BaudRate_Select = ttk.Combobox(self.Control)
        self.BaudRate_Select.place(relx=0.69, rely=0.24, relheight=0.232
                , relwidth=0.157, bordermode='ignore')
        self.BaudRate_Select.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.BaudRate_Select.configure(textvariable=self.BaudRateSelect)

        self.Clear_Message = tk.Button(self.top)
        self.Clear_Message.place(relx=0.856, rely=0.283, height=30, width=110)
        self.Clear_Message.configure(activebackground="#d9d9d9")
        self.Clear_Message.configure(activeforeground="black")
        self.Clear_Message.configure(background="#d9d9d9")
        self.Clear_Message.configure(disabledforeground="#a3a3a3")
        self.Clear_Message.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.Clear_Message.configure(foreground="#000000")
        self.Clear_Message.configure(highlightbackground="#d9d9d9")
        self.Clear_Message.configure(highlightcolor="#000000")
        self.Clear_Message.configure(text='''Clear_Message''')

        self.Download = tk.Button(self.top)
        self.Download.place(relx=0.856, rely=0.433, height=90, width=110)
        self.Download.configure(activebackground="#d9d9d9")
        self.Download.configure(activeforeground="black")
        self.Download.configure(background="#d9d9d9")
        self.Download.configure(disabledforeground="#a3a3a3")
        self.Download.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.Download.configure(foreground="#000000")
        self.Download.configure(highlightbackground="#d9d9d9")
        self.Download.configure(highlightcolor="#000000")
        self.Download.configure(text='''Download''')

        self.Resterun_App = tk.Checkbutton(self.top)
        self.Resterun_App.place(relx=0.85, rely=0.617, relheight=0.112
                , relwidth=0.126)
        self.Resterun_App.configure(activebackground="#d9d9d9")
        self.Resterun_App.configure(activeforeground="black")
        self.Resterun_App.configure(anchor='w')
        self.Resterun_App.configure(background="#d9d9d9")
        self.Resterun_App.configure(compound='left')
        self.Resterun_App.configure(disabledforeground="#a3a3a3")
        self.Resterun_App.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.Resterun_App.configure(foreground="#000000")
        self.Resterun_App.configure(highlightbackground="#d9d9d9")
        self.Resterun_App.configure(highlightcolor="#000000")
        self.Resterun_App.configure(justify='left')
        self.Resterun_App.configure(text='''Reset&Run App''')
        self.Resterun_App.configure(variable=self.che76)

        self.TLabelframe1 = ttk.Labelframe(self.top)
        self.TLabelframe1.place(relx=0.022, rely=0.9, relheight=0.092
                , relwidth=0.812)
        self.TLabelframe1.configure(relief='')
        self.TLabelframe1.configure(text='''Information''')

        self.TSeparator3 = ttk.Separator(self.TLabelframe1)
        self.TSeparator3.place(relx=0.752, rely=0.182, relheight=2.982
                , bordermode='ignore')
        self.TSeparator3.configure(orient="vertical")

        self.TSeparator2 = ttk.Separator(self.TLabelframe1)
        self.TSeparator2.place(relx=0.493, rely=0.182, relheight=2.982
                , bordermode='ignore')
        self.TSeparator2.configure(orient="vertical")

        self.TSeparator1 = ttk.Separator(self.TLabelframe1)
        self.TSeparator1.place(relx=0.259, rely=0.182, relheight=2.982
                , bordermode='ignore')
        self.TSeparator1.configure(orient="vertical")

        self.Label_AppVersion = tk.Label(self.TLabelframe1)
        self.Label_AppVersion.place(relx=0.766, rely=0.364, height=23, width=85
                , bordermode='ignore')
        self.Label_AppVersion.configure(activebackground="#d9d9d9")
        self.Label_AppVersion.configure(activeforeground="black")
        self.Label_AppVersion.configure(anchor='w')
        self.Label_AppVersion.configure(background="#d9d9d9")
        self.Label_AppVersion.configure(compound='left')
        self.Label_AppVersion.configure(disabledforeground="#a3a3a3")
        self.Label_AppVersion.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.Label_AppVersion.configure(foreground="#000000")
        self.Label_AppVersion.configure(highlightbackground="#d9d9d9")
        self.Label_AppVersion.configure(highlightcolor="#000000")
        self.Label_AppVersion.configure(text='''AppVersion:''')

        self.AppVersion = tk.Label(self.TLabelframe1)
        self.AppVersion.place(relx=0.899, rely=0.364, height=23, width=66
                , bordermode='ignore')
        self.AppVersion.configure(activebackground="#d9d9d9")
        self.AppVersion.configure(activeforeground="black")
        self.AppVersion.configure(anchor='w')
        self.AppVersion.configure(background="#d9d9d9")
        self.AppVersion.configure(compound='left')
        self.AppVersion.configure(disabledforeground="#a3a3a3")
        self.AppVersion.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.AppVersion.configure(foreground="#000000")
        self.AppVersion.configure(highlightbackground="#d9d9d9")
        self.AppVersion.configure(highlightcolor="#000000")
        self.AppVersion.configure(text='''00.00.00''')

        self.Checksum = tk.Label(self.TLabelframe1)
        self.Checksum.place(relx=0.629, rely=0.364, height=23, width=85
                , bordermode='ignore')
        self.Checksum.configure(activebackground="#d9d9d9")
        self.Checksum.configure(activeforeground="black")
        self.Checksum.configure(anchor='w')
        self.Checksum.configure(background="#d9d9d9")
        self.Checksum.configure(compound='left')
        self.Checksum.configure(disabledforeground="#a3a3a3")
        self.Checksum.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.Checksum.configure(foreground="#000000")
        self.Checksum.configure(highlightbackground="#d9d9d9")
        self.Checksum.configure(highlightcolor="#000000")
        self.Checksum.configure(text='''0x00000000''')

        self.Label_Checksum = tk.Label(self.TLabelframe1)
        self.Label_Checksum.place(relx=0.506, rely=0.364, height=23, width=75
                , bordermode='ignore')
        self.Label_Checksum.configure(activebackground="#d9d9d9")
        self.Label_Checksum.configure(activeforeground="black")
        self.Label_Checksum.configure(anchor='w')
        self.Label_Checksum.configure(background="#d9d9d9")
        self.Label_Checksum.configure(compound='left')
        self.Label_Checksum.configure(disabledforeground="#a3a3a3")
        self.Label_Checksum.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.Label_Checksum.configure(foreground="#000000")
        self.Label_Checksum.configure(highlightbackground="#d9d9d9")
        self.Label_Checksum.configure(highlightcolor="#000000")
        self.Label_Checksum.configure(text='''File CRC32:''')

        self.Length = tk.Label(self.TLabelframe1)
        self.Length.place(relx=0.382, rely=0.364, height=23, width=78
                , bordermode='ignore')
        self.Length.configure(activebackground="#d9d9d9")
        self.Length.configure(activeforeground="black")
        self.Length.configure(anchor='w')
        self.Length.configure(background="#d9d9d9")
        self.Length.configure(compound='left')
        self.Length.configure(disabledforeground="#a3a3a3")
        self.Length.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.Length.configure(foreground="#000000")
        self.Length.configure(highlightbackground="#d9d9d9")
        self.Length.configure(highlightcolor="#000000")
        self.Length.configure(text='''0x00000000''')

        self.Label_Lenth = tk.Label(self.TLabelframe1)
        self.Label_Lenth.place(relx=0.271, rely=0.364, height=23, width=66
                , bordermode='ignore')
        self.Label_Lenth.configure(activebackground="#d9d9d9")
        self.Label_Lenth.configure(activeforeground="black")
        self.Label_Lenth.configure(anchor='w')
        self.Label_Lenth.configure(background="#d9d9d9")
        self.Label_Lenth.configure(compound='left')
        self.Label_Lenth.configure(disabledforeground="#a3a3a3")
        self.Label_Lenth.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.Label_Lenth.configure(foreground="#000000")
        self.Label_Lenth.configure(highlightbackground="#d9d9d9")
        self.Label_Lenth.configure(highlightcolor="#000000")
        self.Label_Lenth.configure(text='''File Lenth:''')

        self.Address = tk.Label(self.TLabelframe1)
        self.Address.place(relx=0.148, rely=0.364, height=23, width=84
                , bordermode='ignore')
        self.Address.configure(activebackground="#d9d9d9")
        self.Address.configure(activeforeground="black")
        self.Address.configure(anchor='w')
        self.Address.configure(background="#d9d9d9")
        self.Address.configure(compound='left')
        self.Address.configure(disabledforeground="#a3a3a3")
        self.Address.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.Address.configure(foreground="#000000")
        self.Address.configure(highlightbackground="#d9d9d9")
        self.Address.configure(highlightcolor="#000000")
        self.Address.configure(text='''0x08000000''')

        self.Label_StartAddr = tk.Label(self.TLabelframe1)
        self.Label_StartAddr.place(relx=0.014, rely=0.364, height=23, width=86
                , bordermode='ignore')
        self.Label_StartAddr.configure(activebackground="#d9d9d9")
        self.Label_StartAddr.configure(activeforeground="black")
        self.Label_StartAddr.configure(anchor='w')
        self.Label_StartAddr.configure(background="#d9d9d9")
        self.Label_StartAddr.configure(compound='left')
        self.Label_StartAddr.configure(disabledforeground="#a3a3a3")
        self.Label_StartAddr.configure(font="-family {Microsoft YaHei UI} -size 9")
        self.Label_StartAddr.configure(foreground="#000000")
        self.Label_StartAddr.configure(highlightbackground="#d9d9d9")
        self.Label_StartAddr.configure(highlightcolor="#000000")
        self.Label_StartAddr.configure(text='''Start Address:''')

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, tk.Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')
def start_up():
    IAP_tools_support.main()

if __name__ == '__main__':
    IAP_tools_support.main()




