#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Sep 10, 2025 04:37:30 PM CST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m56 -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 1000x600+2625+193
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4164 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "IAP_tools"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::progressbar "$top.tPr55" \
        -length 730 
    vTcl:DefineAlias "$top.tPr55" "DownloadTProgressbar" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.tPr55
    button "$top.but73" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 \
        -font "-family {Microsoft YaHei UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Clear_Message" 
    vTcl:DefineAlias "$top.but73" "Clear_Message" vTcl:WidgetProc "Toplevel1" 1
    button "$top.but74" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 \
        -font "-family {Microsoft YaHei UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Download" 
    vTcl:DefineAlias "$top.but74" "Download" vTcl:WidgetProc "Toplevel1" 1
    ::vTcl::widgets::ttk::labelframe::createCmd "$top.tLa78" \
        -text "Information" -width 731 -height 55 
    vTcl:DefineAlias "$top.tLa78" "TLabelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tLa78
    ttk::separator "$site_3_0.tSe83" \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe83" "TSeparator3" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator "$site_3_0.tSe82" \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe82" "TSeparator2" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator "$site_3_0.tSe81" \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe81" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab85" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Microsoft YaHei UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "StartAddr:" 
    vTcl:DefineAlias "$site_3_0.lab85" "Label_StartAddr" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab91" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Microsoft YaHei UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "AppVersion:" 
    vTcl:DefineAlias "$site_3_0.lab91" "Label_AppVersion" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab92" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Microsoft YaHei UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "00.00.00" 
    vTcl:DefineAlias "$site_3_0.lab92" "AppVersion" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab87" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Microsoft YaHei UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "File Lenth:" 
    vTcl:DefineAlias "$site_3_0.lab87" "Label_Lenth" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab88" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Microsoft YaHei UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "0x00000000" 
    vTcl:DefineAlias "$site_3_0.lab88" "Length" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab86" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Microsoft YaHei UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "0x08000000" 
    vTcl:DefineAlias "$site_3_0.lab86" "Address" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab90" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Microsoft YaHei UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "0x00000000" 
    vTcl:DefineAlias "$site_3_0.lab90" "Checksum" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab89" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Microsoft YaHei UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "File CRC32:" 
    vTcl:DefineAlias "$site_3_0.lab89" "Label_Checksum" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tSe83 \
        -in $site_3_0 -x 0 -relx 0.752 -y 0 -rely 0.182 -width 0 \
        -relwidth 0.003 -height 0 -relheight 2.982 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tSe82 \
        -in $site_3_0 -x 0 -relx 0.492 -y 0 -rely 0.182 -width 0 \
        -relwidth 0.003 -height 0 -relheight 2.982 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tSe81 \
        -in $site_3_0 -x 0 -relx 0.233 -y 0 -rely 0.182 -width 0 \
        -relwidth 0.003 -height 0 -relheight 2.982 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab85 \
        -in $site_3_0 -x 0 -relx 0.014 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.093 -height 0 -relheight 0.418 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab91 \
        -in $site_3_0 -x 0 -relx 0.766 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.418 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab92 \
        -in $site_3_0 -x 0 -relx 0.889 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.081 -height 0 -relheight 0.418 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab87 \
        -in $site_3_0 -x 0 -relx 0.246 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.094 -height 0 -relheight 0.418 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab88 \
        -in $site_3_0 -x 0 -relx 0.356 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.133 -height 0 -relheight 0.418 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab86 \
        -in $site_3_0 -x 0 -relx 0.123 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.104 -height 0 -relheight 0.418 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab90 \
        -in $site_3_0 -x 0 -relx 0.629 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.418 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab89 \
        -in $site_3_0 -x 0 -relx 0.506 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.418 -anchor nw \
        -bordermode ignore 
    ::vTcl::widgets::ttk::labelframe::createCmd "$top.tLa54" \
        -text "Log" -width 730 -height 345 
    vTcl:DefineAlias "$top.tLa54" "Log" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tLa54
    vTcl::widgets::ttk::scrolledtext::CreateCmd "$site_3_0.scr57" \
        -borderwidth 2 -relief groove -background #d9d9d9 -height 75 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 125 
    vTcl:DefineAlias "$site_3_0.scr57" "Message" vTcl:WidgetProc "Toplevel1" 1

    $site_3_0.scr57.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #000000 \
        -insertbackground #000000 \
        -insertborderwidth 3 \
        -selectbackground #d9d9d9 \
        -selectforeground black \
        -width 10 \
        -wrap none
    vTcl:copy_lock $site_3_0.scr57
    place $site_3_0.scr57 \
        -in $site_3_0 -x 0 -relx 0.014 -y 0 -rely 0.073 -width 0 \
        -relwidth 0.975 -height 0 -relheight 0.869 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.tLa54
    ::vTcl::widgets::ttk::labelframe::createCmd "$top.tLa79" \
        -text "State" -width 128 -height 135 
    vTcl:DefineAlias "$top.tLa79" "Connect_State_Labe" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tLa79
    label "$site_3_0.lab84" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Microsoft YaHei UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "State" 
    vTcl:DefineAlias "$site_3_0.lab84" "Connect_State" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab84 \
        -in $site_3_0 -x 0 -relx 0.352 -y 0 -rely 0.444 -width 0 \
        -relwidth 0.289 -height 0 -relheight 0.17 -anchor nw \
        -bordermode ignore 
    checkbutton "$top.che76" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Microsoft YaHei UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify left \
        -text "Reset&Run App" -variable "che76" 
    vTcl:DefineAlias "$top.che76" "Resterun_App" vTcl:WidgetProc "Toplevel1" 1
    ::vTcl::widgets::ttk::labelframe::createCmd "$top.tLa53" \
        -text "Control" -width 956 -height 125 
    vTcl:DefineAlias "$top.tLa53" "Control" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tLa53
    text "$site_3_0.tex65" \
        -background white -font "-family {Microsoft YaHei UI} -size 9" \
        -foreground black -height 32 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 791 \
        -wrap word 
    $site_3_0.tex65 configure -font "TkTextFont"
    $site_3_0.tex65 insert end text
    vTcl:DefineAlias "$site_3_0.tex65" "Text1" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab70" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Microsoft YaHei UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Port:" 
    vTcl:DefineAlias "$site_3_0.lab70" "Label1" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox "$site_3_0.tCo64" \
        -font "-family {Microsoft YaHei UI} -size 9" -textvariable "combobox" 
    vTcl:DefineAlias "$site_3_0.tCo64" "Port_Select" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox "$site_3_0.tCo66" \
        -font "-family {Microsoft YaHei UI} -size 9" \
        -textvariable "COMSelect" 
    vTcl:DefineAlias "$site_3_0.tCo66" "COM_Select" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab71" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Microsoft YaHei UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "COM:" 
    vTcl:DefineAlias "$site_3_0.lab71" "Label2" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox "$site_3_0.tCo67" \
        -font "-family {Microsoft YaHei UI} -size 9" \
        -textvariable "BaudRateSelect" 
    vTcl:DefineAlias "$site_3_0.tCo67" "BaudRate_Select" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab72" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Microsoft YaHei UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Baudrate:" 
    vTcl:DefineAlias "$site_3_0.lab72" "Label3" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but69" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 \
        -font "-family {Microsoft YaHei UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Open_file" 
    vTcl:DefineAlias "$site_3_0.but69" "Open_file" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but68" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 \
        -font "-family {Microsoft YaHei UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Open_Port" 
    vTcl:DefineAlias "$site_3_0.but68" "Open_Port" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tex65 \
        -in $site_3_0 -x 0 -relx 0.01 -y 0 -rely 0.667 -width 0 \
        -relwidth 0.827 -height 0 -relheight 0.237 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 0 -relx 0.031 -y 0 -rely 0.222 -width 0 \
        -relwidth 0.043 -height 0 -relheight 0.244 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo64 \
        -in $site_3_0 -x 0 -relx 0.073 -y 0 -rely 0.24 -width 0 \
        -relwidth 0.103 -height 0 -relheight 0.232 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo66 \
        -in $site_3_0 -x 0 -relx 0.314 -y 0 -rely 0.222 -width 0 \
        -relwidth 0.183 -height 0 -relheight 0.23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 0 -relx 0.272 -y 0 -rely 0.222 -width 0 \
        -relwidth 0.043 -height 0 -relheight 0.244 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo67 \
        -in $site_3_0 -x 0 -relx 0.649 -y 0 -rely 0.222 -width 0 \
        -relwidth 0.185 -height 0 -relheight 0.23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 0 -relx 0.575 -y 0 -rely 0.24 -width 0 \
        -relwidth 0.067 -height 0 -relheight 0.24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but69 \
        -in $site_3_0 -x 0 -relx 0.879 -y 0 -rely 0.592 -width 99 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but68 \
        -in $site_3_0 -x 0 -relx 0.879 -y 0 -rely 0.16 -width 99 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.tLa53
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tPr55 \
        -in $top -x 0 -relx 0.022 -y 0 -rely 0.867 -width 0 -relwidth 0.811 \
        -height 19 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but73 \
        -in $top -x 0 -relx 0.856 -y 0 -rely 0.283 -width 109 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but74 \
        -in $top -x 0 -relx 0.856 -y 0 -rely 0.433 -width 109 -relwidth 0 \
        -height 90 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tLa78 \
        -in $top -x 0 -relx 0.022 -y 0 -rely 0.9 -width 0 -relwidth 0.812 \
        -height 0 -relheight 0.092 -anchor nw -bordermode ignore 
    place $top.tLa54 \
        -in $top -x 0 -relx 0.022 -y 0 -rely 0.267 -width 0 -relwidth 0.811 \
        -height 0 -relheight 0.575 -anchor nw -bordermode ignore 
    place $top.tLa79 \
        -in $top -x 0 -relx 0.844 -y 0 -rely 0.767 -width 0 -relwidth 0.142 \
        -height 0 -relheight 0.225 -anchor nw -bordermode ignore 
    place $top.che76 \
        -in $top -x 0 -relx 0.856 -y 0 -rely 0.617 -width 0 -relwidth 0.126 \
        -height 0 -relheight 0.145 -anchor nw -bordermode ignore 
    place $top.tLa53 \
        -in $top -x 0 -relx 0.022 -y 0 -rely 0.033 -width 0 -relwidth 0.956 \
        -height 0 -relheight 0.208 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

